version: '3'
services:
  model:
    container_name: model
    build: ./frontend
    ports:
      - 3000:3000  

  hal9000:
    container_name: hal9000
    build: ./backend
    ports:
     - 5000:5000
