version: '3'
services:
  model:
    container_name: model
    build: ./frontend
    ports:
      - 5173:5173  

  hal9000:
    container_name: hal9000
    build: ./backend
    ports:
     - 8000:8000
